#!/usr/bin/env bash
# Create redirect
INDEX_COPY="Holberton School for the win!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "$INDEX_COPY" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https:\/\/github.com\/atetheone permanent;' /etc/nginx/sites-available/default
sudo service nginx start
